[Examples] Upgrade to busybox 1.32.0 to avoid linker issues
Using the latest busybox 1.32.0 on more recent distros (Fedora 32)
avoids linker issues like the following ones:

  /usr/bin/ld: util-linux/lib.a(rdate.o): in function `rdate_main':
  rdate.c:(.text.rdate_main+0x150): undefined reference to `stime'
  /usr/bin/ld: coreutils/lib.a(date.o): in function `date_main':
  date.c:(.text.date_main+0x2a4): undefined reference to `stime'
  collect2: error: ld returned 1 exit status